version: '2'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: bin/rails spec
    environment:
      - AUTH_API_CERTIFICATE_BASE64
      - AUTH_API_PRIVATE_KEY_BASE64_1
      - AUTH_API_PRIVATE_KEY_BASE64_2
      - AUTH_API_PRIVATE_KEY_PASS_PHRASE
      - AUTHORIZATION_ENDPOINT
      - DB_USER=postgres
      - RAILS_ENV=test
      - RAILS_LOG_TO_STDOUT=
    links:
      - db:auth-db
  auth-api:
    image: this
    environment:
      - AUTH_API_CERTIFICATE_BASE64
      - AUTH_API_PRIVATE_KEY_BASE64_1
      - AUTH_API_PRIVATE_KEY_BASE64_2
      - AUTH_API_PRIVATE_KEY_PASS_PHRASE
      - AUTHORIZATION_ENDPOINT
      - DB_USER=postgres
      - RAILS_ENV=test
      - RAILS_LOG_TO_STDOUT=1
    links:
      - db:auth-db
  db:
    image: postgres:9.4
  users-api:
    depends_on:
      - auth-api
    environment:
      - DB_USER=postgres
      - RAILS_ENV=test
      - RAILS_LOG_TO_STDOUT=1
    image: partixyz/users-api:0.2.1-8-g860fcc2
    links:
      - db:users-db
