FROM partixyz/docker-ruby

RUN gem install bundler

RUN mkdir -p /parti/auth-api 
WORKDIR /parti/auth-api

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . ./

EXPOSE 3030
CMD ["deploy/docker-cmd.sh"]
