#!/usr/bin/env bash
# vim: ts=2 sw=2

DOCKER_COMPOSE_FILE=deploy/docker-compose-dev2.yml
DEFAULT_SERVICE=auth-api
DEPS_SERVICES=(auth-api users-api)

auth-api() {
  run-docker-compose run --rm auth-api "$@"
}

auth-db() {
  psql auth_test
}

build() {
  run-docker-compose build
}

bundle() {
  users-api bundle
}

clean() {
  rm -rf tmp/*
}

db() {
  run-docker-compose run --rm db "$@"
}

db_setup() {
  run-docker-compose up -d db
  auth-api dockerize -wait tcp://auth-db:5432
  auth-api rails db:setup
  users-api rails db:setup
}

deps() {
  export RAILS_LOG_TO_STDOUT=1
  clean
  db_setup
  run-docker-compose up -d ${DEPS_SERVICES[*]}
}

down() {
  run-docker-compose down
}

logs() {
  run-docker-compose logs -f "$@"
}

ps() {
  run-docker-compose ps "$@"
}

psql() {
  db psql -h db -U postgres "$@"
}

rails() {
  RAILS_LOG_TO_STDOUT= $DEFAULT_SERVICE rails "$@"
}

rspec() {
  RAILS_LOG_TO_STDOUT= $DEFAULT_SERVICE rspec "$@"
}

run-docker-compose() {
  docker-compose -f $DOCKER_COMPOSE_FILE "$@"
}

up() {
  db_setup
  run-docker-compose up -d "$@"
}

users-api() {
  run-docker-compose run --rm users-api "$@"
}

users-db() {
  psql users_test
}
