default: &defaults
  issuer: <%= "http://#{ENV['AUTH_API_EXTERNAL_HOST'] || 'localhost'}:#{ENV['AUTH_API_EXTERNAL_PORT'] || '3030'}" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
