auth-api:
  environment:
    - AUTH_API_CERTIFICATE_BASE64
    - AUTH_API_PRIVATE_KEY_BASE64
    - AUTH_API_PRIVATE_KEY_PASS_PHRASE
    - DB_USER=postgres
    - RAILS_ENV=test
  image: partixyz/auth-api:current
  links:
    - db:auth-db
  ports:
    - 3030:3030
db:
  image: postgres:9.4
  ports:
    - 5432:5432
users-api:
  environment:
    - DB_USER=postgres
    - RAILS_ENV=test
  image: partixyz/users-api:0.1.0-21-g24dc22d
  links:
    - db:users-db
    - auth-api
  ports:
    - 3031:3030
