FROM ruby:2.3

RUN wget https://github.com/jwilder/dockerize/releases/download/v0.2.0/dockerize-linux-amd64-v0.2.0.tar.gz
RUN tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.2.0.tar.gz

RUN gem install bundler

WORKDIR /tmp
COPY Gemfile Gemfile.lock /tmp/
RUN bundle install

RUN mkdir -p /parti/auth-api 
WORKDIR /parti/auth-api

COPY . ./

EXPOSE 3030
CMD ["deploy/docker-cmd.sh"]
