#!/bin/bash
echo -e "\e[46m---------------------------"
echo -e "\e[96mThis is the pre-build test"
echo -e "\e[46m---------------------------"

env
docker -v
docker-compose -v
git --version
git describe --tags --long

exit 0
